version: '3.8'

services:
  ivr-app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ivr-app-prod
    restart: always
    ports:
      - "8081:80"
    networks:
      - ivr-app
    
  ivr-app-admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: ivr-app-admin
    restart: always
    ports:
      - "8080:80"
    networks:
      - ivr-app

networks:
  ivr-app:
    driver: bridge