FROM nginx:latest

WORKDIR /ivr-front


#  Этап  1:  Создаем  образ  с  config.admin.js
COPY . /ivr-front
COPY config.js /ivr-front

# Меняем adminPanelOn на true т.е. включаем админ панель
RUN sed -i 's/adminPanelOn:\s*false/adminPanelOn:\ttrue/g' /ivr-front/config.js

#  Изменяем  конфигурацию  Nginx (если нужно)
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN cat /ivr-front/config.js

#  Перезапускаем  Nginx,  чтобы  изменения  вступили  в  силу
CMD ["nginx", "-g", "daemon off;"] 