version: '3.8'

services:
  ivr-app-testbrunch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ivr-app-testbrunch
    restart: always
    ports:
      - "8082:80"
    networks:
      - ivr-app

networks:
  ivr-app:
    driver: bridge